/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/roles": {
    /**
     * List all roles
     * @description Returns all roles paginated
     */
    get: {
      parameters: {
        query?: {
          /** @description Page number */
          page?: number;
          /** @description Items per page */
          limit?: number;
        };
      };
      responses: {
        /** @description List of roles */
        200: {
          content: {
            "application/json": unknown;
          };
        };
      };
    };
    /**
     * Create a role
     * @description Create a new role
     */
    post: {
      requestBody?: {
        content: {
          "application/json": {
            name?: string;
          };
        };
      };
      responses: {
        /** @description Role created */
        201: {
          content: {
            "application/json": {
              id?: string;
              name?: string;
              created_at?: string;
            };
          };
        };
        /** @description Role already exists */
        400: {
          content: {
            "application/json": {
              message?: string;
            };
          };
        };
      };
    };
  };
  "/roles/{id}": {
    /**
     * Get specific role
     * @description Get specific role
     */
    get: {
      parameters: {
        path: {
          /** @description Role id */
          id: string;
        };
      };
      responses: {
        /** @description Role */
        200: {
          content: {
            "application/json": unknown;
          };
        };
        /** @description Role not found */
        404: {
          content: {
            "application/json": unknown;
          };
        };
      };
    };
    /**
     * Update a role
     * @description Update a role
     */
    put: {
      parameters: {
        path: {
          /** @description Role id */
          id: string;
        };
      };
      requestBody?: {
        content: {
          "application/json": {
            name?: string;
          };
        };
      };
      responses: {
        /** @description Role updated */
        200: {
          content: {
            "application/json": unknown;
          };
        };
        /** @description Role not found */
        404: {
          content: {
            "application/json": unknown;
          };
        };
      };
    };
    /**
     * Delete a role
     * @description Delete a role
     */
    delete: {
      parameters: {
        path: {
          /** @description Role id */
          id: string;
        };
      };
      responses: {
        /** @description Role deleted */
        200: {
          content: never;
        };
        /** @description Role not found */
        404: {
          content: {
            "application/json": unknown;
          };
        };
      };
    };
  };
}

export type webhooks = Record<string, never>;

export type components = Record<string, never>;

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export type operations = Record<string, never>;
