/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


export interface paths {
  "/personas": {
    /** Obtém informações das personas */
    get: {
      responses: {
        /** @description Sucesso */
        200: {
          content: {
            "application/json": unknown;
          };
        };
      };
    };
  };
}

export type webhooks = Record<string, never>;

export type components = Record<string, never>;

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export type operations = Record<string, never>;
